### ISSUE TITLE
Enhanced Apps not showing stats on homepage

### ISSUE THREAD

**Issue by ShlomiD83** [linuxserver/ifai#1050]
Hi All,
Ever since version 2.5.3 enhanced apps do not show stats on home page (i.e Adguard Home, Portainer, qBittorrent, etc..)
Reverting to version 2.5.2 solves the issue.

Please assist.
Thanks!

**Comment by keriati** [comment]
Probably fixed in https://github.com/linuxserver/Heimdall/pull/1049

**Comment by ShlomiD83** [comment]
@keriati was this included in the development image?

**Comment by keriati** [comment]
Yes

**Comment by ShlomiD83** [comment]
@keriati I've tried the development image yesterday and it was even worse, all the apps stopped showing stats.
with 2.5.3 some apps still showed stats.

**Comment by ShlomiD83** [comment]
I've tried again with the development image and it seems to work now.
maybe I tried with an image that didn't include the fix.

**Comment by keriati** [comment]
Fix is from 9pm yesterday evening (CET), probably you got an earlier version. Development is now pretty active so it could have some issues...
If you are at it, maybe try the export feature on the item list page. If you encounter any problems please report.
